server:
  port: 8081
  servlet:
    context-path: /communitys
  # 应用的上下文路径，也可以称为项目路径，是构成url地址的一部分。
  #server.servlet.context-path不配置时，默认为/，如：localhost：8080/xxxxxx
  #当server.servlet.context-path有配置时，比如/demo，此时的访问方式为localhost：8080/demo/xxxxxx

spring:
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: yc12138**

  # 邮箱设置
  mail:
    host: smtp.sina.com
    port: 465
    username: yc_lil@sina.com
    password: 26f00b67de92ef69
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0  # Redis启动后默认提供了16个数据库，默认进入第0号数据库
  #kafka配置
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000  # 3000ms自动提交一次
  #Elasticsearch配置
  data:
    elasticsearch:
      #声明集群的名字
      cluster-name: nowcoder
      #声明节点地址，ip:端口  tcp-9300 / http-9200
      cluster-nodes: 127.0.0.1:9300

  main:
    allow-bean-definition-overriding: true

  # Quartz配置
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5

#如果xml文件跟mapper在同一个目录下，则application.yml中不需要配置下面这个。
#mybatis.mapper-locations=classpath:mapper/*.xml
mybatis:
  type-aliases-package: com.yc.communitys.entity
  configuration:
    # 自动生成id: useGeneratedKeys=true
    use-generated-keys: true
    # 设置下划线和首字母大写驼峰匹配
    map-underscore-to-camel-case: true

# caffeine配置，本地缓存，缓存帖子列表
caffeine:
  posts:
    # 缓存15页
    max-size: 15
    # 缓存到期时间，设置成180秒
    expire-seconds: 180

logging:
  level:
    org.springframework.data.convert.CustomConversions: ERROR

# 网站域名
communitys:
  path:
    domain: http://localhost:8081
    # 设置上传资源的路径，比如用户头像
    upload: E:/IDEA/IdeaProjects/upload

